for (var a=[],i=0;i<86;++i) a[i]=i;

 let pergunta = ["POR QUANTO TEMPO DEVEMOS LAVAR AS MÃOS ANTES DE ASSUMIR UMA ESTAÇÃO?", "QUAIS OS QUATRO FUNDAMENTOS BÁSICOS DO MC DONALD’S (QSLV)?", "QUAL A TEMPERATURA DA TOSTADEIRA (PRINCIPAL/AUXILIAR) ?", "QUAIS OS CONDIMENTOS DE UM MCNIFICO BACON EM QUANTIDADE?", "QUAL ALTURA E QUANTAS GRAMAS DE SAL PARA SALGAR AS MC FRITAS?", "QUAL A CAPACIDADE MÁXIMA DA ESTUFA DE TORTAS E QUAL A TEMPERATURA DA MESMA?", "QUAL A TEMPERATURA DE EXTRAÇÃO DO SUNDAE?", "QUAL A VELOCIDADE DE EXTRAÇÃO DO SUNDAE?", "QUAL A TEMPERATURA AMBIENTE DO SALÃO?", "QUAL A ALTURA IDEAL DA CASQUINHA?", "QUAL A TEMPERATURA DE EXTRAÇÃO DAS COBERTURAS DE SUNDAE?", "QUAL É O TEMPO DE AQUECIMENTO DA TOSTADEIRA?", "QUAL É O MAXIMO DE CARNES QUE PODEM SER ATIVADAS NA CHAPA DE REGULAR POR PLATEN?", "QUAL É O TEMPO DE FRITURA DAS TORTAS?", "QUAL É O AJUSTE DE COMPRESSÃO DA TOSTADEIRA?", "QUAL O ÂNGULO PARA RASPAR A CHAPA?", "QUAL SEGUNDO PASSO DO ATENDIMENTO?", "QUAL SIGNIFICADO DA ROTAÇÃO P.V.P.S?", "QUAL TEMPO DE FRITURA DAS SEGUINTES CARNES: MC CHICKEN e JUNIOR", "QUAL TEMPO MAXIMO DE REMOÇÃO DAS SEGUINTES CARNES: 10:1, PIC, 4:1, 3:1", "QUAL TEMPO DE VIDA DOS PÃES EM AREA APÓS ABERTO?", "QUAIS OS RENDIMENTOS DOS SEGUINTES CONDIMENTOS: KETCHUP, ALFACE", "QUAL PESO IDEAL DE UMA CASQUINHA PRONTA?", "QUANTOS ML POSSUI: 1 OZ, 1/3 OZ, 2/3 OZ, 1/40 OZ E L1/2 OZ?", "QUAL TEMPERATURA SUPERIOR E INFERIOR DA CHAPA?", "QUAL TEMPO DE FRITURA DA MC FRITAS?", "QUANTOS TIROS DE COBERTURA COLOCAMOS EM UM MC FLURRY EM OZ ?", "QUANTO PESA UMA MC FRITAS KIDS?", "QUAL TEMPO DE VIDA DA MC FRITAS NA ENCESTADORA ELETRÔNICA?", "QUAL É A TEMPERATURA DA MESA DE CONDIMENTAÇÃO?", "QUAL TEMPO DE VIDA DO NUGGETS NA UHC?", "QUAL TEMPO DE VIDA DA CARNE DE JUNIOR NA UHC?", "QUANTO PESA A CARNE DE 3:1?","QUAL TEMPO IDEAL COMPLETO PARA 'CONDIMENTAÇÃO' DE UM BIG MAC?", "QUAL TEMPO DE CARAMELIZAÇÃO DO PÃO?", "QUAL MÁXIMO DE NUGGETS QUE PODEM SER COLOCADOS POR GAVETA?", "QUAL MÁXIMO DE CARNES DE MC CHICKEN PODEM SER COLOCADOS POR GAVETA?", "QUAL TEMPO DE VIDA SECUNDÁRIO DA CEBOLA SHOYU?","QUAL Á TEMPERATURA INTERNA DE INTEGRIDADE DAS CARNES VERMELHAS?","QUAL TEOR DE GORDURA DA MISTURA DO SUNDAE?","QUAL TEMPO DE AQUECIMENTO DA CHAPA?","QUANTOS ITENS POSSO COLOCAR EM UM SACO B?","QUAL É O TEMPO DE VIDA SECUNDÁRIO DO SUCO?","QUAL RENDIMENTO DA CEBOLA SHOYU?","QUAL TERCEIRO PASSO DO ATENDIMENTO?","QUAL RENDIMENTO DO PICLES?","QUAL TEMPO DE VIDA PRIMÁRIO DAS CARNES VERMELHAS?","QUAL É A TEMPERATURA DA MAQUINA DE CAFÉ?","QUAL TEOR DE GORDURA DA CARNE DE 10:1?","QUAL DIÂMETRO DO PÃO DE BIG MAC?","QUAL DIÂMETRO DO PÃO DE CHEDDAR?","QUAL É A QUANTIDADE/TEMPO DE EXTRAÇÃO DO REFRIGERANTE ZERO?","QUAL É A QUANTIDADE/TEMPO DE EXTRAÇÃO DO REFRIGERANTE NORMAL?","QUAL É O PRIMEIRO PASSO DO ATENDIMENTO?","QUANTO PESA A CARNE DE PIC ?", "QUANTO DE MOLHO TASTY COLOCAMOS EM UM BIG TASTY?","QUANTO DE MOLHO MAIONESE COLOCAMOS EM UM DUPLO SALADA?","QUANTO DE MOLHO MAIONESE COLOCAMOS EM UM MC NIFICO BACON?","QUANTO DE CEBOLA CHEDDAR/SHOYU COLOCAMOS EM UM CHEDDAR?","QUANTO DE CEBOLA CRISPY COLOCAMOS EM UM BIG MAC?","QUAIS TODOS OS CONDIMENTOS DE UM BIG MAC? ","QUANTAS GRAMAS DE ALFACE COLOCAMOS EM UM MC CHICKEN? QUAL ALFACE?","QUANTAS GRAMAS DE ALFACE COLOCAMOS EM UM BIG TASTY? QUAL ALFACE?","QUANTO DE MOSTARDA COLOCAMOS EM UM TRIPLO CB?","QUANTO DE KETCHUP COLOCAMOS EM UM TRIPLO BURGUER BACON?","QUANTAS GRAMAS DE CEBOLA FRESCA COLOCAMOS EM UM BIG TASTY?","QUANTO DE MOLHO CHEDDAR COLOCAMOS EM UM CHEDDAR?","QUANTO DE MOLHO MAIONESE COLOCAMOS EM UM MC CHICKEN?","QUANTAS FATIAS DE BACON COLOCAMOS EM UM TRIPLO CB?","QUANTAS FATIAS DE BACON COLOCAMOS EM UM DUPLO BURGUER BACON?","QUANTAS FATIAS DE QUEIJO COLOCAMOS EM UM HB?","QUANTO DE MOSTARDA COLOCAMOS EM UM CB?","QUANTOS PICLES COLOCAMOS EM UM QUARTERÃO?","QUANTAS GRAMAS DE CEBOLA COLOCAMOS EM UM QUARTERÃO? QUAL CEBOLA?","QUANTAS FATIAS DE QUEIJO COLOCAMOS EM UM DUPLO QUARTERÃO? QUAL QUEIJO?","QUANTO DE KETCHUP COLOCAMOS EM UM DUPLO QUARTEIRÃO?","QUANTO DE MOLHO E QUAL MOLHO COLOCAMOS EM UM CLUB HOUSE?","QUAIS OS CINCO PASSOS DE ATENDIMENTO NO SALÃO?","QUAL PESO EM OZ DAS MC FRITAS KIDS, PEQUENA, MÉDIA E GRANDE?","QUANTOS PANOS TEMOS QUE TER NA ESTAÇÃO DAS MC FRITAS?","QUAL EMPILHAMENTO MÁXIMO DE CAIXAS DA CEBOLA FRESCA E DA ALFACE AMERICANA NAS CÂMARAS?","QUAL EMPILHAMENTO MÁXIMO DE CAIXAS DE BATATA E MC CHICKEN NAS CÂMARAS?","CITE O SÉTIMO CONCEITO DA UHC.","O QUE SIGNIFICA PDT?","EM QUANTAS SEMANAS O PDT É DIVIDIDO ?","O QUE E A COOLTURA DE SERVIÇO E QUAL SEU PROPOSITO?"];

let resposta = ["20 SEGUNDOS", "QUALIDADE, SERVIÇO, LIMPEZA E VALOR", "TOSTADEIRA PRINCIPAL 293°C E AUXILIAR 204°", "MOSTARDA 1/40 OZ KETCHUP ½ OZ 7 GRAMAS DE CEBOLA FRESCA MAIONESE 1/3OZ ALFACE AMERICANA 28 GRAMAS 2 FATIAS DE TOMATE 1 FATIA DE QUEIJO CHEDDAR 2 FATIAS DE BACON 1 CARNE 4:1,", "20 CM/ 4 GRAMAS DE SAL", "48 TORTAS / TEMPERATURA DE 66°C A 82°C", "R: -9°C A -8°C", "5 A 7,5 OZ EM 10 SEGUNDOS","24° A 27° GRAUS", "7,5 CM", "46°C A 52°C", "15 MINUTOS", "8 CARNES", "6 MINUTOS", "5 D", "45° GRAUS","TOMADA DO PEDIDO", "PRIMEIRO QUE VENCE/ PRIMEIRO QUE SAI","3:15 e 3:15", "10:1= 18 SEG,   PIC= 15 SEG,    4:1= 15,    SEG 3:1= 15 SEG", "2 HORAS", "KETCHUP POUCH= 77 A 79 SANDUICHES POR POUCH, ALFACE= 45,40 SANDUICHES POR KG", "99 GRAMAS", "1 OZ= 30 ML,  1/3 OZ= 10 ML,  2/3 OZ= 20 ML,   1/40 OZ= 0,6 M,  L ½ OZ= 15 ML", "SUPERIOR 218°C INFERIOR 177°C", "3 MINUTOS E 10 SEGUNDOS", "2 TIROS DE ½ CADA", "31 GRAMAS", "24 HORAS", "59°C A 63°C", "20 MINUTOS", "15 MINUTOS", "150 GRAMAS", "17 A 22 SEGUNDOS", "22 SEGUNDOS", "24 NUGGETS", "6 CARNES", "48 HORAS NA EMBALAGEM ORIGINAL SOBRE REFRIGERAÇÃO", "APARTIR DE 70°C", "5%", "20 MINUTOS", "5 A 6 ITENS", "7 DIAS", "70,42 SANDUICHES POR KG", "PAGAMENTO", "255 SANDUICHES POR KG", "90 DIAS", "86° A 92°C","17% A 20%", "9,5 A 9,8 CM", "9,5 A 10,2", "400 ML EM 12 SEGUNDOS", "450 ML EM 12 SEGUNDOS", "CUMPRIMENTO", "90 GRAMAS", "1 OZ = 30 ML", "1/3 OZ= 10 ML", "1/3 OZ= 10 ML", "7 GRAMAS", "NADA", "1/3 OZ MOLHO BIG MAC CLUB BASE, 3,5 GRAMAS DE CEBOLA REIDRATADA CLUB BASE, 12 GRAMAS DE ALFACE AMERICANA CLUB BASE, 2 PICLES CLUB, 1 FATIA DE QUEIJO CHEDDAR BASE, 1 CARNE 10:1 CLUB E 1 CARNE 10:1 BASE", "22 GRAMAS DE ALFACE AMERICANA","28 GRAMAS DE ALFACE AMERICANA","1/40 OZ = 0,6 ML","1/3 OZ= 10 ML","10 GRAMAS","1 OZ= 30ML","2/3 OZ= 20 ML","NADA","2 FATIAS", "NADA","1/40 OZ= 0,6 ML"," 2 PICLES","7 GRAMAS DE CEBOLA FRESCA","2 FATIAS DE QUEIJO CHEDDAR","½ OZ = 15 ML 8","1/3 OZ = 10 ML NA COROA E 1/3 = 10 ML NA BASE DE MOLHO BIG MAC","RECEPCIONAR/ DIRECIONAR/ ACOMODAR/ ATENDER E AGRADECER","KIDS= 1 OZ,  PEQUENA= 2,5 OZ,   MÉDIA= 3,5 OZ,    GRANDE= 5 OZ","2 PANOS","8 CAIXAS","6 CAIXAS","UHC É O CORAÇÃO DA COZINHA","PROGRAMA DE DESENVOLVIMENTO DE FUNCIONÁRIOS","3 FASES, PLANEJAMENTO, AÇÃO E CONTROLE","COOLTURA DE SERVIÇO E VOCE SER VC MESMO TRATANDO AS PESSOAS COMO VOCE GOSTARIA DE SER TRATADO E GERAR BONS MOMENTOS SENDO VC MESMO"];

let text_pergunta = document.getElementById("texto");
let text_resposta = document.getElementById("resposta");

function shuffle(array) {
  var tmp, current, top = array.length;
  if(top) while(--top) {
    current = Math.floor(Math.random() * (top + 1));
    tmp = array[current];
    array[current] = array[top];
    array[top] = tmp;
  }
  return array;
}

a = shuffle(a);
console.log(a);
let txt_resposta = document.getElementById("resposta");
let cont = 0;
let botao_pergunta = document.getElementById("nextButton");
botao_pergunta.onclick = () => {  
	botao_voltar.style.display = "block"
	text_resposta.style.display = "none"
	console.log(cont)
    text_pergunta.innerHTML = pergunta [a[cont]];
    text_resposta .innerHTML =  resposta [a[cont]];
    cont++;
	if(cont == 86) {
		botao_pergunta.style.display = "none";
	} else {
		botao_pergunta.style.display = "block";
	}
}

let botao_resposta = document.getElementById("answer");
botao_resposta.onclick = () => {
	txt_resposta.style.display = "block";
}


document.addEventListener("keydown", (event) => {
	if (event.key === "ArrowRight") {
		botao_pergunta.onclick()
	}
	if (event.key === "Enter") {
		botao_resposta.onclick()
	}
	if (event.key === "ArrowLeft") {
		botao_voltar.onclick()
	}
}) 

const botao_voltar = document.getElementById("backButton");

botao_voltar.onclick = () => {
	cont = cont - 2;
	if (cont <= 0) {
		botao_voltar.style.display = "none";
	}
	text_pergunta.innerHTML = pergunta [a[cont]];
    text_resposta .innerHTML =  resposta [a[cont]];
	cont++;
}

